# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = [""]
description = ""
language = "javascript"
manifest_version = 2
name = "json2vcl"
service_id = ""

[local_server]

  [local_server.backends]

    [local_server.backends.fastly_api]
      url = "https://api.fastly.com"

[setup]

  [setup.backends]

    [setup.backends.fastly_api]
      address = "api.fastly.com"
      port = 443
